Make add_widget no longer an alias, but call addWidget instead
pytest-dev/pytest-qt pull request #326
Opened 2020-12-10 20:56 UTC by oliveira-mauricio

We use a subclass of QtBot with a custom `addWidget`. However, when using `add_widget`, which was not redefined in our subclass, it would call the alias in QtBot, calling the parent's addWidget, without our customizations, leading to undesired behavior.

Instead of using an alias, I've added an implementation that works for subclasses as well.

2020-12-10 22:41 UTC, nicoddemus requested changes
Thanks @oliveira-mauricio!

Currently we have those kind of aliases for all methods, would you mind applying the same change for all of them? I suggest you just group them all in the same part of the file, instead of next to the original methods like today.

```python
# pep-8 aliases

def add_widget(self, *args, **kwargs):
    return self.addWidget(*args, *kwargs)

def wait_active(self, *args, **kwargs):
    return self.waitActive(*args, *kwargs)

def wait_exposed(self, *args, **kwargs):
    return self.waitExposed(*args, *kwargs)

# and so on
```

I also think in those cases we don't really need tests (but thanks for adding one anyway).

2020-12-11 13:47 UTC, nicoddemus approved these changes

2020-12-11 13:52 UTC, merged

2020-12-11 13:52 UTC, nicoddemus commented
Thanks @oliveira-mauricio!

2020-12-17 12:49 UTC, The-Compiler commented
Hmm, I haven't tried yet, but wouldn't this actually break autocompletion in IDEs because they don't know the function signature anymore?

2020-12-17 13:00 UTC, nicoddemus commented
You are right, we lose that benefit when using the aliases.